[package]
name = "dropspace"
version = "1.0.0"
authors = []

[addresses]
dropspace="b1a51a62b2e7a753e7888a91b3fdf14496cbbc657d3b6905ba6c66c178c93d21"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosToken]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token"

[dev-dependencies]
